apiVersion: v2
name: janus-idp-workflows
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: "0.0.1"

dependencies:
  - name: backstage
    repository: https://janus-idp.github.io/helm-backstage
    version: "2.11.4"
  - name: postgresql-persistent
    repository: https://sclorg.github.io/helm-charts
    version: "0.0.3"
    condition: postgresql-persistent.enabled
  - name: serverless-knative
    repository: "file://charts/serverless-knative"
    version: "0.1.0"
    condition: serverless-knative.enabled
  - name: sonataflow-operator
    repository: "file://charts/sonataflow-operator"
    version: "0.1.2"
    condition: sonataflow-operator.enabled
  - name: workflows
    repository: https://parodos.dev/serverless-workflows-helm
    version: "0.2.0"
    condition: workflows.enabled
