name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add dependencies
        run: |
          helm repo add backstage https://janus-idp.github.io/helm-backstage
          helm repo add postgresql-persistent https://sclorg.github.io/helm-charts
          helm repo add workflows https://parodos.dev/serverless-workflows-helm

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: chart-releaser.yaml
          charts_dir: charts/kubernetes
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
